/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service banner + the list of available endpoints. */
        get: operations["getIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe + current sim tick. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current discrete simulation tick. */
        get: operations["getTick"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Derived observation metrics (economy, trust, diplomacy, log). */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The entire composed world state (all regions + all agents). */
        get: operations["getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All regions (villages). */
        get: operations["listRegions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A single region by id. */
        get: operations["getRegion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All agents (residents + treasuries). */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A single agent by id. */
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events from the append-only log, optionally since a seq. */
        get: operations["getLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/log/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A stable digest of the whole log + its length.
         * @description The digest is a deterministic hash of the event log. Two runs with the same seed
         *     produce the same digest — this is the determinism/replay guarantee in observable form.
         */
        get: operations["getLogDigest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Discrete sim-engine time. The protocol orders by log `seq`, not `tick` (audit G5). */
        Tick: number;
        Error: {
            error: string;
        };
        Metrics: {
            tick: components["schemas"]["Tick"];
            regions: {
                total: number;
                recognized: number;
                unrecognized: number;
            };
            agents: {
                total: number;
                residents: number;
                treasuries: number;
                totalCurrency: number;
                totalCredit: number;
                /** @description Gini coefficient of resident currency (0 = equal, ~1 = concentrated). */
                currencyGini: number;
            };
            log: {
                length: number;
                digest: string;
                /** @description Count of events by `type`. */
                eventTypes: {
                    [key: string]: number;
                };
            };
        };
        /** @enum {string} */
        AgentRole: "artisan" | "merchant" | "broker" | "treasury";
        /** @enum {string} */
        ValueProfile: "strict" | "lenient";
        /** @enum {string} */
        RecognitionStatus: "unrecognized" | "recognized";
        /**
         * @description How a village translates another village's certificates (§4-A).
         * @enum {string}
         */
        ForeignCertStance: "absorb" | "map" | "reexamine" | "reject";
        SchemaLedgerEntry: {
            schemaId: string;
            label?: string;
        };
        VerificationPolicy: {
            acceptedSchemaIds: string[];
            rejectUnknownSchemas: boolean;
        };
        DiplomacyPolicy: {
            defaultStance: components["schemas"]["ForeignCertStance"];
            overrides: {
                [key: string]: components["schemas"]["ForeignCertStance"];
            };
        };
        Institutions: {
            schemaLedger: components["schemas"]["SchemaLedgerEntry"][];
            verificationPolicy: components["schemas"]["VerificationPolicy"];
            diplomacyPolicy: components["schemas"]["DiplomacyPolicy"];
        };
        /** @description Who proposed a region's founding. */
        Proposer: {
            /** @constant */
            kind: "genesis";
        } | {
            /** @constant */
            kind: "experimenter";
            note?: string;
        } | {
            /** @constant */
            kind: "emergence";
            sourceRegion: string;
            reason: string;
            cohort: string[];
        };
        /**
         * @example {
         *       "id": "umi",
         *       "displayName": "Umi",
         *       "institutions": {
         *         "schemaLedger": [],
         *         "verificationPolicy": {
         *           "acceptedSchemaIds": [],
         *           "rejectUnknownSchemas": false
         *         },
         *         "diplomacyPolicy": {
         *           "defaultStance": "reexamine",
         *           "overrides": {}
         *         }
         *       },
         *       "status": "recognized",
         *       "proposer": {
         *         "kind": "genesis"
         *       },
         *       "foundedAtSeq": 0
         *     }
         */
        RegionState: {
            id: string;
            displayName: string;
            institutions: components["schemas"]["Institutions"];
            status: components["schemas"]["RecognitionStatus"];
            proposer: components["schemas"]["Proposer"];
            /** @description The log seq at which the region was founded (NOT the sim tick). */
            foundedAtSeq: number;
        };
        Balances: {
            /** @description Non-transferable, slow trust accrual (§3-B). */
            credit: number;
            /** @description Transferable medium of exchange (§3-B). */
            currency: number;
        };
        AgentState: {
            /** @description name@region — stable identity across migration. */
            id: string;
            /** @description Current residence (changes on migration). */
            region: string;
            role: components["schemas"]["AgentRole"];
            /** @description base64 Ed25519 public key ("" for a treasury account). */
            publicKey: string;
            balances: components["schemas"]["Balances"];
            reputation: number;
            valueProfile: components["schemas"]["ValueProfile"];
        };
        WorldState: {
            /** @description Regions keyed by id. */
            regions: {
                [key: string]: components["schemas"]["RegionState"];
            };
            /** @description Agents keyed by id. */
            agents: {
                [key: string]: components["schemas"]["AgentState"];
            };
        };
        /**
         * @example {
         *       "seq": 2,
         *       "tick": 0,
         *       "type": "region.founded",
         *       "actor": "world",
         *       "payload": {
         *         "status": "recognized",
         *         "proposer": {
         *           "kind": "genesis"
         *         }
         *       }
         *     }
         */
        AlmaEvent: {
            /** @description Global, 0-based, monotonic position in the log (the canonical order). */
            seq: number;
            tick: components["schemas"]["Tick"];
            /**
             * @description Event kind. Known kinds on this branch: region.founded,
             *     region.institution.changed, region.recognized, agent.admitted,
             *     agent.migrated, agent.decided, economy.settled, system.tick.
             */
            type: string;
            /** @description The originating subject (an identifier), or "world" for the engine. */
            actor: string;
            /**
             * @description Event content, opaque to the log itself; meaning belongs to higher layers.
             *     The richest payload is `economy.settled`, which carries a `receipt` Certificate
             *     and the signed balance deltas (see SettlementPayload). Other event kinds carry
             *     their own shapes, so a generic object is the fallback branch.
             */
            payload: components["schemas"]["SettlementPayload"] | {
                [key: string]: unknown;
            };
        };
        SettlementEntry: {
            agentId: string;
            currencyDelta: number;
            creditDelta: number;
            reputationDelta: number;
        };
        /** @description The payload of an `economy.settled` event, authored by the environment. */
        SettlementPayload: {
            entries: components["schemas"]["SettlementEntry"][];
            receipt: components["schemas"]["Certificate"];
            memo: {
                from: string;
                to: string;
                amount: number;
                fee: number;
            };
        };
        /**
         * @description The universal vouch-core certificate envelope. Not returned as a top-level body by
         *     any read route, but embedded in `economy.settled` event payloads as the transaction
         *     receipt (schemaId "alma.tx/receipt/v1").
         */
        Certificate: {
            /** @constant */
            version: "alma-cert/v1";
            /** @example ed25519 */
            suite: string;
            /** @description name@region */
            issuer: string;
            /** @description name@region */
            subject: string;
            schemaId: string;
            claims: {
                [key: string]: unknown;
            };
            /** @description ISO 8601 (deterministic, derived from tick) */
            issuedAt: string;
            /** @description base64 */
            signature: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service identity and endpoint index. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "service": "vouch observation",
                     *       "endpoints": [
                     *         "/health",
                     *         "/tick",
                     *         "/metrics",
                     *         "/state",
                     *         "/regions",
                     *         "/regions/:id",
                     *         "/agents",
                     *         "/agents/:id",
                     *         "/log?since=N",
                     *         "/log/digest"
                     *       ]
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        service: "vouch observation";
                        endpoints: string[];
                    };
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is up; reports the current tick. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ok": true,
                     *       "tick": 8
                     *     }
                     */
                    "application/json": {
                        /** @constant */
                        ok: true;
                        tick: components["schemas"]["Tick"];
                    };
                };
            };
        };
    };
    getTick: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current tick. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tick": 8
                     *     }
                     */
                    "application/json": {
                        tick: components["schemas"]["Tick"];
                    };
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A snapshot of derived metrics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "tick": 8,
                     *       "regions": {
                     *         "total": 1,
                     *         "recognized": 1,
                     *         "unrecognized": 0
                     *       },
                     *       "agents": {
                     *         "total": 4,
                     *         "residents": 3,
                     *         "treasuries": 1,
                     *         "totalCurrency": 300,
                     *         "totalCredit": 48,
                     *         "currencyGini": 0.08564814814814814
                     *       },
                     *       "log": {
                     *         "length": 61,
                     *         "digest": "91a22c60",
                     *         "eventTypes": {
                     *           "region.founded": 1,
                     *           "agent.admitted": 4,
                     *           "system.tick": 8,
                     *           "agent.decided": 24,
                     *           "economy.settled": 24
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Metrics"];
                };
            };
        };
    };
    getState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full world state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldState"];
                };
            };
        };
    };
    listRegions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every region in the world. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionState"][];
                };
            };
        };
    };
    getRegion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The region id (the `region` string, e.g. "umi"). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The region. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionState"];
                };
            };
            /** @description No region with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "region not found"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every agent in the world. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentState"][];
                };
            };
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent id (`name@region`, e.g. "ada@umi"). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentState"];
                };
            };
            /** @description No agent with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "agent not found"
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getLog: {
        parameters: {
            query?: {
                /** @description Return events with `seq >= since`. Defaults to 0 (the whole log). */
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The events at or after `since`, in seq order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlmaEvent"][];
                };
            };
        };
    };
    getLogDigest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The log digest and length. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "digest": "91a22c60",
                     *       "length": 61
                     *     }
                     */
                    "application/json": {
                        /** @example 91a22c60 */
                        digest: string;
                        length: number;
                    };
                };
            };
        };
    };
}
